coolapp/config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  get 'restaurants/index'
  resources :restaurants

  root 'restaurants#index'

end

coolapp/app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants
end

coolapp/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 1 }
  validates :address, presence: true, length: { minimum: 1 }
  validates :phone, presence: true, length: { minimum: 1 }, format: { with: /\d{3}-\d{3}-\d{4}/,message: "invalid phone number" }
  validates :description, presence: true, length: { minimum: 1 }

  belongs_to :owner
end

coolapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

coolapp/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_owner!, except: [:index, :show]

  def new
    @restaurant = current_owner.restaurants.new
  end

  def edit
    @restaurant = current_owner.restaurants.find_by_id(params[:id])
    return redirect_to restaurants_url, notice: "cannot edit restaurant" unless @restaurant
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = current_owner.restaurants.new(restaurant_params)
    @restaurant.owner = current_owner

    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def update
    @restaurant = current_owner.restaurants.find_by_id(params[:id])

    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = current_owner.restaurants.find_by_id(params[:id])
    return redirect_to restaurants_url, notice: "cannot delete restaurant" unless @restaurant
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :description)
  end
end

coolapp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

coolapp/app/helpers/application_helper.rb
module ApplicationHelper
end

coolapp/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

coolapp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

coolapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coolapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

coolapp/app/views/restaurants/_form.html.erb
<%= form_for :restaurant, url: restaurants_path do |f| %>

  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@restaurant.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

coolapp/app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

coolapp/app/views/restaurants/index.html.erb
<h1>Listing Restaurants</h1>



<% if owner_signed_in? %>
  <%= link_to 'New restaurant', new_restaurant_path %>
  <%= link_to current_owner.email, edit_owner_registration_path %>
  <%= link_to 'Log Out', destroy_owner_session_path, method: :delete %>
<% else%>
  <%= link_to 'Sign Up', new_owner_registration_path %>
  <%= link_to 'Log In', new_owner_session_path %>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone Number</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>

  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.phone %></td>
      <td><%= restaurant.description %></td>
      <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
      <% if restaurant.owner == current_owner%>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant_path(restaurant),
                method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

coolapp/app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

coolapp/app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @restaurant.phone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<%= link_to 'Back', restaurants_path %>
<td><%= link_to 'Edit', edit_restaurant_path(@restaurant) %></td>

coolapp/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My List', controller: 'restaurants' %>